export const FETCH_DATA_TASK = 'FETCH_DATA_TASK'
export const FETCH_DATA_TASK_SUCCESS = 'FETCH_DATA_TASK_SUCCESS'
export const FETCH_DATA_TASK_FAILED = 'FETCH_DATA_TASK_FAILED'

export const FILTER_TASK = 'FILTER_TASK'
export const FILTER_TASK_SUCCESS = 'FILTER_TASK_SUCCESS'

export const ADD_NEW_DATA = 'ADD_NEW_DATA'
export const ADD_NEW_DATA_SUCCESS = 'ADD_NEW_DATA_SUCCESS'


export const DELETE_TASK_DATA = 'DELETE_TASK_DATA'
export const DELETE_TASK_DATA_SUCCESS = 'DELETE_TASK_DATA_SUCCESS'



export const UPDATE_TASK_DATA = 'UPDATE_TASK_DATA'
export const UPDATE_TASK_DATA_SUCCESS = 'UPDATE_TASK_DATA_SUCCESS'